apiVersion: v1
kind: Service
metadata:
  name: external-service-kuservice
spec:
  type: LoadBalancer
  selector:
    app: external-service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8080